#!/bin/bash
export PATH="$PATH:$PWD"
CONFIRMED=$(cat confirmed)


#This is for setting the confirmation of the mac address
while [ "$(($CONFIRMED))" -eq 0 ];
do

trap 'exit' INT    
./write_mac.py

#CONFIRMATION
sudo l2ping -c 2 $(cat store_mac.txt) &> ping_output
CONFIRMED=$(bash to_binary.sh $(cat ping_output))
done

echo $CONFIRMED > confirmed

#CONSTANT PING
 > time_to_excel
while [ 1 ]
trap 'exit' INT
do
 > saved_time
{ time ./ping_command; } &> presence
cat presence >> saved_time
FULL_DATA=$(python3 time_manip.py) 
echo $FULL_DATA
echo $FULL_DATA >> time_to_excel
done
