#!/usr/bin/python

import time

import os
import sys
import datetime

now = datetime.datetime.now()
with open('/home/pi/Research/Civil/filestuff','a+') as f:
    f.write('YOOOOO\t'+str(now.hour)+':'+str(now.minute)+'\n')
    f.close()
